import { Header } from '@/components/layout/Header'
import type { Metadata } from 'next'
import { Jost } from 'next/font/google'
import Footer from '@/components/layout/Footer'
import '../styles/globles.css'

const jost = Jost({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={jost.className}>
        <Header />
        {children}
        <Footer />
        </body>
    </html>
  )
}
